import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Brandon Wu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

     {/* useRef + scrolling */}
     <h1>Brandon Wu</h1>
    </div>
  )
}
